# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76aeb26d4f21f0d7c5f7e5da776f556614d6257a68ef2c1fa95cb27f40b229664c9f0ddb57edb9d93794dbb427605f475daba3eece4241cceb5d5648a4b68930

test:
  secret_key_base: 774a7fd944e3cec1b33aa7bcaddd06193e0ff1ae37819136e917d4a61d53569ed47fc6f7abba3bf25e1698cfb02e3514e5426cb153bc027c251b7883716bd672

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
